#!/bin/bash

set -u # Variables must be explicit
set -e # If any command fails, fail the whole thing
set -o pipefail

source utilities/add_key.sh -vvv
source utilities/init.sh

ansible-playbook sync.yaml -vvv
